-- 코드를 입력하세요
SELECT a.CAR_ID,
CASE WHEN EXists(
    SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    where a.CAR_ID=b.CAR_ID
    and '2022-10-16' BETWEEN b.START_DATE AND b.END_DATE)
then '대여중'
else '대여 가능'
END as AVAILABILITY
FROM (SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) a
ORDER BY CAR_ID desc;

